matrix:
    include:
      - language: go
        go:
          - 1.x
        script:
          - go build Golang/main.go
      
      - language: ruby 
        rvm:
          - 2.5.0 
        script:
          - ruby Ruby/gol.rb
      
      - language: lua 
        script:
          - lua Lua/GameOfLife.lua
